### ISSUE TITLE
Implement the BufferIntrospective operator

### ISSUE THREAD

**Issue by alexandru** [monixio/monix#113]
We need a new operator with this signature:

```scala
trait Observable[+T] {
  def bufferIntrospective(os: OverflowStrategy): Observable[Seq[T]]
}
```

What this will do is to buffer signals for as long as the downstream subscriber is busy. And after the downstream subscriber is available again for `onNext`, then it sends the buffered signals as a `Seq`.

Implementation sample: https://gist.github.com/dvtomas/e47bce4f8849da9721dc

**Comment by dvtomas** [comment]
As I've commented on gist, perhaps these signatures would be more appropriate:

```scala
trait Observable[+T] {
  def bufferIntrospective: Observable[Seq[T]]

  def bufferIntrospective(maxSize: Int): Observable[Seq[T]]
}
```

They resemble the signatures of `Observable.buffer`, as does the principle of operation

**Comment by dvtomas** [comment]
I've updated `bufferIntrospective` implementation in the gist, I believe it is correct now. I also have some (two :) unit tests, but it is difficult to present them here as they use some custom helpers, and I also use Li Haoyi's µTest for testing. If there's interest, though, I can try to port them somehow..

Anyway, I now have in mind an even more general "introspective" operator, that `bufferIntrospective` could be implemented in terms of, but I need to think about it more.

**Comment by alexandru** [comment]
This is already on `master`, closing.
