### ISSUE TITLE
ScalaJS Dependency resolution error when jquery is also in the classpath.

### ISSUE THREAD

**Issue by alonsodomin** [monixio/monix#135]
When using version `2.0-M1` in a ScalaJS project which also includes `jquery` among its dependencies, the following compiler error from the ScalaJS compiler plugin shows up:

```
[trace] Stack trace suppressed: run last consoleApp/compile:resolvedJSDependencies for the full output.
[error] (consoleApp/compile:resolvedJSDependencies) org.scalajs.core.tools.jsdep.JSLibResolveException: Some references to JS libraries could not be resolved:
[error] - Ambiguous reference to a JS library: jquery.js
[error]   Possible paths found on the classpath:
[error]   - scala/tools/nsc/doc/html/resource/lib/jquery.js
[error]   - META-INF/resources/webjars/jquery/1.11.1/jquery.js
```

To reproduce the error, configure an ScalaJS project using following settings:

```scala
libraryDependencies ++= Seq(
  "io.monix"  %%% "monix-reactive" % "2.0-M1",
  "be.doeraene" %%% "scalajs-jquery" % "0.9.0"
)
jsDependencies ++= Seq(
  "org.webjars" % "jquery" % "1.11.1" / "jquery.js" minified "jquery.min.js"
)
```

The dependency collision seems to come from the fact that Monix is pulling the scala compiler as a compile-time dependency. This makes the ScalaJS compiler plugin find two `jquery.js` files in the classpath, one that comes from the actual dependency in the project and another one that comes from the Scala compiler.

**Comment by ngbinh** [comment]
it is a problem with `scala.js` searches. I get around it by using `jsDependencyFilter`:
```scala
    // remove "jquery.js" jsDeps 
    jsDependencyFilter := (_.filter(!_.relPath.endsWith("jquery.js"))),
```

**Comment by alonsodomin** [comment]
Where do you apply that `jsDependecyFilter`? I mean, in my case I DO want `jquery.js` in my classpath, not just the one from the scala compiler...

It seems that the other way of solving is by using a syntax like the following:
```scala
jsDependencies += <your dep> / "1.11.1/jquery.js"
```

In some way I see two issues here. One being the fact that the scala compiler shouldn't be in my compile classpath. The other one is that the Scala.JS compiler plugin should probably be more clever when resolving this kind of dependencies...

**Comment by alexandru** [comment]
@alonsodomin the issue should be fixed in the latest `2.0-M2`, as the `scala-compiler` dependency is now marked as `provided` (and actually will be gone for Scala 2.11 in future releases, but stays for now). This means that your own project shouldn't import `scala-compiler` anymore.

Can you please check?

**Comment by alonsodomin** [comment]
@alexandru tested this today, no more ambiguous refererence when compiling a ScalaJS project which also includes jQuery.

You can close this. thanks!

**Comment by alexandru** [comment]
Cool :-)
