### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by AlexanderRay** [monixio/monix#139]
Hi, 

doc links are broken 

[doc 1.2](https://monix.io/docs/1.2/api/)
[doc 2.0-M2](https://monix.io/docs/2.0-M2/api/)

can you correct them please

**Comment by alexandru** [comment]
Sorry @AlexanderRay, I'm in the middle of a release that's taking forever due to problems. Will fix.

**Comment by alexandru** [comment]
In the meantime, see [doc 1.1](https://monix.io/docs/1.1/api/).

**Comment by AlexanderRay** [comment]
thanks.

I'm looking for reactive streams in scala.js, and think monix would be a good solution ..

**Comment by alexandru** [comment]
@AlexanderRay fixed.
