### ISSUE TITLE
Totally confused (*not a useful github issue)

### ISSUE THREAD

**Issue by PhilAndrew** [monixio/monix#145]
I am totally confused by the number of streaming and flow processing libraries and am unable to compare and make a decision as to what is most suitable for me. Does anyone else feel like this?

**Comment by alexandru** [comment]
Probably there are other people feeling like this, yes.

**Comment by PhilAndrew** [comment]
The problem is that to make a decision I must go in depth and use one of these, and then use another and use another in order to see what is good and bad, but the amount of time and learning is quite high.

Its like Java Hibernate vs other methods in the past, if you didn't really get to know Hibernate in depth you didn't understand it and therefore didn't see what was good about it and couldn't make a fair comparison. Had to go in deep to fully understand.

**Comment by alexandru** [comment]
I feel you @PhilAndrew, but as a library author, my view will naturally be biased, so it won't help you much.

If you want the difference in phylosophy between Monix and Akka Streams, I wrote a (biased) blogpost about it that still holds: https://alexn.org/blog/2015/09/06/monifu-vs-akka-streams.html

Cheers,
