### ISSUE TITLE
`BehaviorSubject` and `ReplaySubject` don't clean up subscribers immediately if subscription is stopped

### ISSUE THREAD

**Issue by xicmiah** [monixio/monix#147]
Subscriber instances created by running `Observable#firstL` on hot observable (at least with `BehaviorSubject`) get cleaned up only when underlying observable pushes an element.

Reproducible example: https://gist.github.com/xicmiah/bfcf9dac0c74db8904018b37a5e3b96a

**Comment by alexandru** [comment]
I can confirm. Some notes:

- this isn't `Observable.firstL` that leaks, the problem being in the implementation of `BehaviorSubject` (and `ReplySubject`)
- basically if an initial state needs to be served, the implementation doesn't notice the subscriber stopped until the next event is sent
- this becomes noticeable with `BehaviorSubject` when you `take(1)`, which is basically what `firstL` is doing
- fix is easy, will make it in the next release

Thanks @xicmiah for taking the time to investigate. The [hint with ConnectableSubscriber](https://gitter.im/monixio/monix?at=5739a1c1ae26c1967f9ed422) pinpointed the problem.

**Comment by alexandru** [comment]
Fixed and released in `2.0-RC3`
