### ISSUE TITLE
A Thank You

### ISSUE THREAD

**Issue by ches** [monixio/monix#159]
Not an issue, but just wanted to say a loud "thank you" for the thoughtful packaging decision of `monix-execution`!

I'll look forward to trying out the rest of Monix in due time, but everything in `monix-execution` is something I've wanted 100 times in programs that need just a little more than standard library Futures, and the going recommendation has been "use Akka whenever a scheduler is required", which is kind of like saying "my other car is a tank". This has been needed in a quality, well-tested, lightweight package for a long time.

**Comment by alexandru** [comment]
Thanks @ches, I'm glad it's useful.
