### ISSUE TITLE
Missing `takeUntil` on `Observable`

### ISSUE THREAD

**Issue by ziggystar** [monixio/monix#162]
I want to end an `Observable` once another `Observable` switches. I think this could be achieved with a method `takeUntil(other: Observable[_])` analogously to `dropUntil`.

**Comment by alexandru** [comment]
@ziggystar OK, will happen, not sure when. If you'd like to give it a shot, you can also send a PR :-P

In the meantime you could play with `switchMap`:

```scala
val trigger = myTriggerObservable.headF.completed

Observable.fromIterable(Seq(source, trigger)).switchMap(identity)
```

**Comment by alexandru** [comment]
@ziggystar the alternative I outlined above doesn't work. Sorry, I'm tired. I mean, my description of `switch` is correct, but it doesn't do what you want.

OK, here's another approach:

```scala
val trigger = Observable.now(true) ++ myTriggerObservable.headF.completed ++ Observable.now(false)
Observable.combineLatest2(source, trigger)
  .takeWhile(_._2).map(_._1)
```
