### ISSUE TITLE
Task to Future conversion

### ISSUE THREAD

**Issue by pjan** [monixio/monix#198]
Hi Alex,

In order to provide compatibility between `Task` and some of the existing scala libraries out there, I currently experience it useful to have some kind of `future` operator, which pretty much starts running the `Task` and captures its result in a `Future`.

disregarding implicit `Scheduler`s and `ExecutionContext`s here, it pretty much has the following implementation.

```scala
class Task[T] {
  ...
  def future: Future[T] = {
    val promise = Promise[T]()
    this.runAsync { result => promise.complete(result }
    promise.future
  }
}
```

I'm currently doing this through an extension (value class wrapping around `Task`), but was wondering whether there would be interest / if it could be added to the instance itself.

Kindest,
pjan

**Comment by volth** [comment]
Task#runAsync returns CancellableFuture which is compatible with scala.concurrent.Future
https://github.com/monixio/monix/blob/69d31e86a3f968ecb00e50b87eb11f218197281b/monix-eval/shared/src/main/scala/monix/eval/Task.scala#L88

**Comment by pjan** [comment]
Thanks for pointing this out. My bad. Closing this.
