### ISSUE TITLE
Include number in name of threads

### ISSUE THREAD

**Issue by lukestephenson** [monixio/monix#204]
When using [Scheduler.fixedPool](https://github.com/monixio/monix/blob/13021b735320ecd76581158716557df0d7d1dcf4/monix-execution/jvm/src/main/scala/monix/execution/schedulers/SchedulerCompanionImpl.scala#L305) and similar methods that create a ThreadPool, all threads in the pool have the same name.

Ideally the threads should have different names to assist with investigating issues when looking at the logs.

Suggest a name contention of `{poolName}-number` where number is incremented each time a thread is created.

If there are no objections, I'll submit a PR for this change.

**Comment by alexandru** [comment]
@lukestephenson sure, go ahead with the PR.
