### ISSUE TITLE
Task: add a way to override the Scheduler used

### ISSUE THREAD

**Issue by alexandru** [monixio/monix#209]
Context: [August 15, 2016 11:56 PM](https://gitter.im/monixio/monix?at=57b22c6b5a4ad610567d3628) by @Diagoras

> What about something like Task(someExpensiveIoCall())? I'd expect cancelling that Task to try and cancel the thread the IO call is running on, so if it uses wait() or an InterruptibleChannel we stop waiting.

We need the equivalent of `Observable.subscribeOn`, but for `Task`.

**Comment by Diagoras** [comment]
@alexandru I think you may have quoted the wrong part of our conversation, you probably wanted:

> I'm considering switching from ScalaZ's Task to Monix's - props for all the awesome work! I've looked through the documentation and one thing still confuses me - since runAsync is the only place we pass a Scheduler and it effectively completes your Task, how do you specify which thread pool to run specific functions?

> For example, with ScalaZ I might do:
```scala
for {
result1 <- Task(someExpensiveCpuCall())(cpuThreadPool)
result2 <- Task(someExpensiveIoCall())(ioThreadPool)
} yield (result1, result2)
```
> Can Monix Task do that? If so, how?

Not that an issue about interrupting threads when cancelled wouldn't be appreciated as well! ;)

**Comment by alexandru** [comment]
@Diagoras that's fine. There's already a solution on master, will be available in the next release.

On interrupting threads, it won't happen. For one because there is no correspondence between threads and `Task`. Tasks don't require the presence of multi-threading. But also because nobody does it, not even Java's own `CompletableFuture.cancel`. And as I tried explaining, you don't even have a way to do it, as `stop()` is deprecated and will go away, whereas `interrupt()` doesn't work as you think it does.

Cheers,

**Comment by Diagoras** [comment]
@alexandru That's great to hear, looking forward to the new release. I understand your reasons for avoiding interrupting threads, as you pointed out not only does `CompletableFuture` not do this but neither does ScalaZ's `Task`. I don't think I'm the person you talked to about `Thread.stop()` and `Thread.interrupt()` in Gitter, but those are still good points.

**Comment by alexandru** [comment]
@Diagoras cool. So the ability to override the `Scheduler` is in `2.0-RC11`. You now have `executeOn` as a method on `Task` instances and an override of `fork` that accepts a `Scheduler`.
