### ISSUE TITLE
Task.sequence for Option

### ISSUE THREAD

**Issue by Diagoras** [monixio/monix#219]
It'd be nice to have a way to go from `Option[Task[A]]` to `Task[Option[A]]` without having to transform the Option to a collection and back again. Even something as simple as this would be nice:

```scala
def sequence[A](maybe: Option[Task[A]]): Task[Option[A]] =
    Task.sequence(maybe.toList) map (_.headOption)
```

**Comment by guersam** [comment]
For now, you can do something like this with `monix-cats` or `monix-scalaz`:
```scala
import monix.eval.Task
import monix.cats._
import cats.implicits._

val some = Option(Task(1)).sequence
val none = Option.empty[Task[Int]].sequence
```

**Comment by alexandru** [comment]
@Diagoras itțs a cool use-case, but is covered by both Cats (and I believe by Scalaz as well) and is out of scope for Monix.

If you're curious, what @guersam showing is covered by the [Traverse](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Traverse.scala#L83) type-class. Cats can do this better than we can.

**Comment by Diagoras** [comment]
Oh, I know. I just thought it might be a nice bit of sugar, like how `sequence` for collections is kind of sugar over ScalaZ/Cats `sequenceU/sequence`. What you say makes sense, though, so I'll close this ticket.
