### ISSUE TITLE
add `task.async()` as a suger

### ISSUE THREAD

**Issue by hepin1989** [monixio/monix#220]
Add `async()` method to instance methods eg:
```scala
def async():Task.fork(this)
```
just like `memorize`

**Comment by alexandru** [comment]
Shouldn't we name it 'fork' as well ? Was thinking we need an asyncBoundary with this meaning:

```
task.flatMap(x => Task.fork(Task.unit).map(_ => x))
```

**Comment by alexandru** [comment]
I have opened #227 with more details. This is now a duplicate, so closing, with the progress to be tracked in #227.
