### ISSUE TITLE
Deadlock when the right conditions are met

### ISSUE THREAD

**Issue by Diagoras** [monixio/monix#230]
Hey @alexandru, I finally managed to reproduce that weird bug I mentioned. Looks like it requires you to block a Task inside of another Task, where the inner Task uses onErrorHandleWith and both are run on the same scheduler. Changing any of those conditions seems to fix the problem.

...I have no idea what's going on here, but hopefully you'll have a better idea. The repo where it's reproduced is linked at the bottom of this comment, the good stuff is in Main.scala

https://github.com/Diagoras/monix-bug-example

**Comment by alexandru** [comment]
Thanks @Diagoras, will take a look.
