### ISSUE TITLE
New logo design

### ISSUE THREAD

**Issue by alexandru** [monixio/monix#245]
Proposal for a new logo, made by myself in Inkscape :-) with an initial inspiration from our designer at @eloquentix, such that:

- it's still an M from Monix
- it resembles Scala's logo on purpose, rotated with 90 degrees - which is cool, because it signals orthogonality :-)
- it's a hexagon, to be compatible with other logos from Typelevel

For comparison:

- Typelevel: https://goo.gl/kCy0RZ
- Doobie: https://goo.gl/1H1o4Q
- Shapeless: https://goo.gl/JVZvkh
- Ensime: https://goo.gl/go8LsH

First version (rejected):

![monix-200](https://cloud.githubusercontent.com/assets/11753/19351454/86e4e4ea-9164-11e6-911c-fb37c2b86afe.png)

Second version:

800px:

![monix-800](https://cloud.githubusercontent.com/assets/11753/19381432/30ee1426-9204-11e6-93ef-ce4c27a51e97.png)

400px:

![monix-400](https://cloud.githubusercontent.com/assets/11753/19381371/f5804e04-9203-11e6-8f76-9141e7815ba1.png)

100px:

![monix-100](https://cloud.githubusercontent.com/assets/11753/19381378/fb204e22-9203-11e6-84fb-e7245b8640de.png)

32px:

![monix-32](https://cloud.githubusercontent.com/assets/11753/19381389/074e0162-9204-11e6-92aa-520c5d80377d.png)

**Comment by aoprisan** [comment]
It's looking really good, I like it quite a lot.

**Comment by mihaisoloi** [comment]
Really cool! But I think that the edges of the hexagon should be flatter, i.e. the vertices should be sharper, so that when put on stickers it would mesh with the typelevel logos in a honeycomb-like structure

**Comment by alexandru** [comment]
@mihaisoloi 😃😄😆 I know what you mean, problem is I don't like sharp edges, I mean, those corners are round on purpose. But I'll try out a sharp version as well.

**Comment by Taig** [comment]
I find it really beautiful as well. But I too think that you should maintain sticker compatibility ;) Maybe you could give the doobie style a try? Keep the edges straight, but use rounded corners. As a a compromise.

**Comment by BennyHill** [comment]
https://www.stickermule.com/user/1070745037/stickers As mentioned ^^, if you keep the same shape/dimensions as the TL ones (1.73" x 2"), people can then add the Monix ones to their honeycombes.

...red?

**Comment by alexandru** [comment]
Yeah, OK, I'm working on another version.

**Comment by BennyHill** [comment]
:+1:

**Comment by alexandru** [comment]
@mihaisoloi @BennyHill @Taig we now have a new version. I got rid of the rounded corners for now, because those corners don't look nice when the icon is small, @Taig being right.

**Comment by Taig** [comment]
I still like it. Imho not as slick as tour initial proposal, but still sexy and sticker compatible 👍

**Comment by etorreborre** [comment]
It's a very nice logo!

**Comment by schrepfler** [comment]
I like the second version better. I would try a third version for 32px size only where the curvy waves on the letter m are replaced with straight lines.

**Comment by alexandru** [comment]
@schrepfler will try. The 32px version is basically the favicon of the website.
