### ISSUE TITLE
Avoid runtime reflection

### ISSUE THREAD

**Issue by Taig** [monixio/monix#247]
In version 2.0.3 runtime reflection was [introduced](https://github.com/monixio/monix/blob/v2.0.3/monix-execution/jvm/src/main/scala/monix/execution/schedulers/LocalBatchingExecutor.scala#L126) which caused my ProGuard optimized Android app to crash without further manual configuration. If possible, it would be desirable to avoid runtime reflection entirely.

**Comment by alexandru** [comment]
@Taig This is released in latest version 2.0.5
