### ISSUE TITLE
Integration with Cats

### ISSUE THREAD

**Issue by alexandru** [monixio/monix#89]
Cats is a new, modular and down to earth alternative for Scalaz. Monifu should integrate cats-core. This means providing implementation for relevant type-classes and possibly using some of its defined types.

Whether this will happen as a separate sub-project (maybe `monifu-cats`), or as a direct dependency, it remains to be seen. The only problem I worry about right now is to not have conflicts with the cats-core (e.g. Monifu's Task vs a future Cats Task, see #88), but hopefully `cats-core` will remain light.

Planning this for 2.0, because this will likely break the current API.

**Comment by ngbinh** [comment]
:+1:

**Comment by alexandru** [comment]
Integration with Cats is on `master` and fairly good.
